require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AdsDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'AdsDemoTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'AdsDemo-tvOS' do
  # Pods for AdsDemo-tvOS

  target 'AdsDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
